default_language_version:
  python: python3.10
files: src|tests
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Run black
        stages: [commit]
        language: system
        entry: black --check --diff
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Run flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        name: Run mypy
        stages: [commit]
        language: system
        entry: mypy
        types: [python]
