name: Code CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt install cmake
          sudo apt install libzmq3-dev

      - name: Build pmacFilterControl
        run: |
          mkdir ${GITHUB_WORKSPACE}/prefix
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/prefix
          make install

      - name: Test pmacFilterControl
        run: |
          python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip
          pip install .[dev]
          PMAC_FILTER_CONTROL=${GITHUB_WORKSPACE}/prefix/bin/pmacFilterControl pytest -v tests
